// GENERATED by acceptance-entrypoint-generator — DO NOT EDIT

mod runtime {
    include!("../acceptance/runtime/mod.rs");
}
mod steps {
    include!("../acceptance/steps/cli_surface_steps.rs");
}

use runtime::World;
use std::collections::HashMap;

#[test]
fn built_in_excluded_directory_is_never_scanned_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), ".git/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn built_in_excluded_directory_is_never_scanned_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "target/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn built_in_excluded_directory_is_never_scanned_example_3() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "node_modules/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn built_in_excluded_directory_is_never_scanned_example_4() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "__pycache__/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn built_in_excluded_directory_is_never_scanned_example_5() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "vendor/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn built_in_excluded_directory_is_never_scanned_example_6() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "dist/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn built_in_excluded_directory_is_never_scanned_example_7() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), ".next/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn explicitly_passing_the_parent_does_not_re_include_a_built_in_excluded_subdirectory_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "proj/alpha.rs".to_string());
    example.insert(
        "right_file".to_string(),
        "proj/node_modules/beta.rs".to_string(),
    );
    example.insert("args".to_string(), "proj".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn explicitly_passing_the_parent_does_not_re_include_a_built_in_excluded_subdirectory_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "proj/alpha.rs".to_string());
    example.insert("right_file".to_string(), "proj/target/beta.rs".to_string());
    example.insert("args".to_string(), "proj".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn a_built_in_excluded_directory_passed_directly_is_still_excluded_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "node_modules/alpha.rs".to_string());
    example.insert("right_file".to_string(), "node_modules/beta.rs".to_string());
    example.insert("args".to_string(), "./node_modules".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn a_twin_outside_built_in_excluded_directories_is_still_reported_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn repeated_exclude_flags_union_their_patterns_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert(
        "args".to_string(),
        "--exclude **/alpha.rs --exclude **/beta.rs ./src".to_string(),
    );
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn repeated_exclude_flags_union_their_patterns_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "gen/beta.rs".to_string());
    example.insert(
        "args".to_string(),
        "--exclude **/gen/** --exclude **/legacy/** ./src ./gen".to_string(),
    );
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn a_gitignored_path_is_not_scanned_when_git_is_available_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ignore_pattern".to_string(), "generated/".to_string());
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "generated/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a git work tree with a git executable available",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a git work tree with a git executable available]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a gitignore entry \"<ignore_pattern>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a gitignore entry \"<ignore_pattern>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn dogfood_run_stays_clean_with_gitignore_awareness_on_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "the drywall project source directory at \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the drywall project source directory at \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a git work tree with a git executable available",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a git work tree with a git executable available]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn gitignore_awareness_silently_no_ops_when_git_is_unavailable_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch("no git executable is available", &mut world, &example);
    assert!(
        result.success,
        "step failed [no git executable is available]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"a,b,sum\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"accumulate_sum\" and identifiers \"x,y,total\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stderr is empty", &mut world, &example);
    assert!(
        result.success,
        "step failed [stderr is empty]: {}",
        result.message
    );
}
