// GENERATED by acceptance-entrypoint-generator — DO NOT EDIT

mod runtime {
    include!("../acceptance/runtime/mod.rs");
}
mod steps {
    include!("../acceptance/steps/jsts_detection_steps.rs");
}

use runtime::World;
use std::collections::HashMap;

#[test]
fn structural_duplicate_in_a_js_or_ts_source_pair_is_reported_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("min_score".to_string(), "0.82".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("ext".to_string(), "ts".to_string());
    example.insert("right_file".to_string(), "src/beta.ts".to_string());
    example.insert("left_file".to_string(), "src/alpha.ts".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the reported score is at least \"<min_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the reported score is at least \"<min_score>\"]: {}",
        result.message
    );
}

#[test]
fn structural_duplicate_in_a_js_or_ts_source_pair_is_reported_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("min_score".to_string(), "0.82".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("ext".to_string(), "js".to_string());
    example.insert("right_file".to_string(), "src/beta.js".to_string());
    example.insert("left_file".to_string(), "src/alpha.js".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the reported score is at least \"<min_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the reported score is at least \"<min_score>\"]: {}",
        result.message
    );
}

#[test]
fn each_js_ts_function_form_is_a_reportable_analysis_unit_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "js".to_string());
    example.insert("left_file".to_string(), "src/alpha.js".to_string());
    example.insert("right_file".to_string(), "src/beta.js".to_string());
    example.insert("structure".to_string(), "function-declaration".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn each_js_ts_function_form_is_a_reportable_analysis_unit_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "ts".to_string());
    example.insert("left_file".to_string(), "src/alpha.ts".to_string());
    example.insert("right_file".to_string(), "src/beta.ts".to_string());
    example.insert("structure".to_string(), "arrow-function".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn each_js_ts_function_form_is_a_reportable_analysis_unit_example_3() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "ts".to_string());
    example.insert("left_file".to_string(), "src/alpha.ts".to_string());
    example.insert("right_file".to_string(), "src/beta.ts".to_string());
    example.insert("structure".to_string(), "class-method".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn each_js_ts_function_form_is_a_reportable_analysis_unit_example_4() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "js".to_string());
    example.insert("left_file".to_string(), "src/alpha.js".to_string());
    example.insert("right_file".to_string(), "src/beta.js".to_string());
    example.insert(
        "structure".to_string(),
        "exported-named-function".to_string(),
    );
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn grammar_is_auto_detected_from_file_extension_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "tsx".to_string());
    example.insert("left_file".to_string(), "src/alpha.tsx".to_string());
    example.insert("right_file".to_string(), "src/beta.tsx".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn grammar_is_auto_detected_from_file_extension_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "jsx".to_string());
    example.insert("left_file".to_string(), "src/alpha.jsx".to_string());
    example.insert("right_file".to_string(), "src/beta.jsx".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn lang_forces_a_grammar_on_a_non_standard_extension_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "ts".to_string());
    example.insert("left_file".to_string(), "src/alpha.txt".to_string());
    example.insert("right_file".to_string(), "src/beta.txt".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "--lang ts ./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn lang_forces_a_grammar_on_a_non_standard_extension_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "js".to_string());
    example.insert("left_file".to_string(), "src/alpha.inc".to_string());
    example.insert("right_file".to_string(), "src/beta.inc".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "--lang js ./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
}

#[test]
fn mixed_language_directory_yields_one_merged_output_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("right_ext".to_string(), "ts".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("left_twin".to_string(), "src/b.rs".to_string());
    example.insert("right_file".to_string(), "src/c.ts".to_string());
    example.insert("left_ext".to_string(), "rs".to_string());
    example.insert("right_twin".to_string(), "src/d.ts".to_string());
    example.insert("left_file".to_string(), "src/a.rs".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a \"<left_ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<left_ext>\" file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<left_ext>\" file \"<left_twin>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<left_ext>\" file \"<left_twin>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<right_ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<right_ext>\" file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a \"<right_ext>\" file \"<right_twin>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<right_ext>\" file \"<right_twin>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<left_twin>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<left_twin>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<right_file>\" and \"<right_twin>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<right_file>\" and \"<right_twin>\"]: {}",
        result.message
    );
}

#[test]
fn unparsable_js_ts_source_is_an_error_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "ts".to_string());
    example.insert("file".to_string(), "src/broken.ts".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "2".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<file>\" containing source that fails to parse",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<file>\" containing source that fails to parse]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stderr is not empty", &mut world, &example);
    assert!(
        result.success,
        "step failed [stderr is not empty]: {}",
        result.message
    );
}

#[test]
fn unparsable_js_ts_source_is_an_error_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("ext".to_string(), "js".to_string());
    example.insert("file".to_string(), "src/broken.js".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "2".to_string());

    let result = steps::dispatch(
        "a \"<ext>\" file \"<file>\" containing source that fails to parse",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a \"<ext>\" file \"<file>\" containing source that fails to parse]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stderr is not empty", &mut world, &example);
    assert!(
        result.success,
        "step failed [stderr is not empty]: {}",
        result.message
    );
}
