// GENERATED by acceptance-entrypoint-generator — DO NOT EDIT

mod runtime {
    include!("../acceptance/runtime/mod.rs");
}
mod steps {
    include!("../acceptance/steps/duplicate_detection_steps.rs");
}

use runtime::World;
use std::collections::HashMap;

#[test]
fn structural_duplicate_across_files_is_reported_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());
    example.insert("min_score".to_string(), "0.82".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [stdout reports a duplicate pair for \"<left_file>\" and \"<right_file>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the reported score is at least \"<min_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the reported score is at least \"<min_score>\"]: {}",
        result.message
    );
}

#[test]
fn unrelated_functions_produce_no_pair_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("left_structure".to_string(), "accumulate_sum".to_string());
    example.insert("right_structure".to_string(), "parse_config".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"<left_structure>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"<left_structure>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"<right_structure>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"<right_structure>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn dogfood_run_on_own_source_exits_clean_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("path".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "the drywall project source directory at \"<path>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the drywall project source directory at \"<path>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<path>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<path>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn function_below_a_size_gate_is_not_a_candidate_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("lines".to_string(), "3".to_string());
    example.insert("nodes".to_string(), "25".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a structurally identical function",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a structurally identical function]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn function_below_a_size_gate_is_not_a_candidate_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("lines".to_string(), "6".to_string());
    example.insert("nodes".to_string(), "15".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a structurally identical function",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a structurally identical function]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn pairs_are_sorted_by_score_descending_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("high_score".to_string(), "0.95".to_string());
    example.insert("low_score".to_string(), "0.84".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a duplicate pair scoring \"<high_score>\" and a duplicate pair scoring \"<low_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a duplicate pair scoring \"<high_score>\" and a duplicate pair scoring \"<low_score>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the pair scoring \"<high_score>\" is reported before the pair scoring \"<low_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the pair scoring \"<high_score>\" is reported before the pair scoring \"<low_score>\"]: {}",
        result.message
    );
}

#[test]
fn threshold_flag_gates_reporting_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("pair_score".to_string(), "0.84".to_string());
    example.insert("args".to_string(), "--threshold 0.90 ./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());
    example.insert("reported".to_string(), "false".to_string());

    let result = steps::dispatch(
        "a duplicate pair scoring \"<pair_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a duplicate pair scoring \"<pair_score>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the pair is reported equals \"<reported>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the pair is reported equals \"<reported>\"]: {}",
        result.message
    );
}

#[test]
fn threshold_flag_gates_reporting_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("pair_score".to_string(), "0.84".to_string());
    example.insert("args".to_string(), "--threshold 0.80 ./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());
    example.insert("reported".to_string(), "true".to_string());

    let result = steps::dispatch(
        "a duplicate pair scoring \"<pair_score>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a duplicate pair scoring \"<pair_score>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the pair is reported equals \"<reported>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the pair is reported equals \"<reported>\"]: {}",
        result.message
    );
}

#[test]
fn size_gate_flags_override_defaults_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("lines".to_string(), "3".to_string());
    example.insert("nodes".to_string(), "25".to_string());
    example.insert("args".to_string(), "--min-lines 2 ./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());
    example.insert("reported".to_string(), "true".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a structurally identical function",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a structurally identical function]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the pair is reported equals \"<reported>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the pair is reported equals \"<reported>\"]: {}",
        result.message
    );
}

#[test]
fn size_gate_flags_override_defaults_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("lines".to_string(), "6".to_string());
    example.insert("nodes".to_string(), "15".to_string());
    example.insert("args".to_string(), "--min-nodes 10 ./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());
    example.insert("reported".to_string(), "true".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with \"<lines>\" source lines and \"<nodes>\" normalized nodes]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a structurally identical function",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a structurally identical function]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the pair is reported equals \"<reported>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the pair is reported equals \"<reported>\"]: {}",
        result.message
    );
}

#[test]
fn json_output_format_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("pair_count".to_string(), "0".to_string());
    example.insert("args".to_string(), "--format json ./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust source set producing \"<pair_count>\" duplicate pairs",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust source set producing \"<pair_count>\" duplicate pairs]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stdout is valid JSON", &mut world, &example);
    assert!(
        result.success,
        "step failed [stdout is valid JSON]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the JSON contains \"<pair_count>\" pair objects",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the JSON contains \"<pair_count>\" pair objects]: {}",
        result.message
    );
}

#[test]
fn json_output_format_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("pair_count".to_string(), "1".to_string());
    example.insert("args".to_string(), "--format json ./src".to_string());
    example.insert("exit_code".to_string(), "1".to_string());

    let result = steps::dispatch(
        "a Rust source set producing \"<pair_count>\" duplicate pairs",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust source set producing \"<pair_count>\" duplicate pairs]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stdout is valid JSON", &mut world, &example);
    assert!(
        result.success,
        "step failed [stdout is valid JSON]: {}",
        result.message
    );
    let result = steps::dispatch(
        "the JSON contains \"<pair_count>\" pair objects",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [the JSON contains \"<pair_count>\" pair objects]: {}",
        result.message
    );
}

#[test]
fn exclude_flag_suppresses_matching_files_from_scanning_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("left_file".to_string(), "src/alpha.rs".to_string());
    example.insert("right_file".to_string(), "src/beta.rs".to_string());
    example.insert("structure".to_string(), "accumulate_sum".to_string());
    example.insert("left_ids".to_string(), "a,b,sum".to_string());
    example.insert("right_ids".to_string(), "x,y,total".to_string());
    example.insert("args".to_string(), "--exclude **/beta.rs ./src".to_string());
    example.insert("exit_code".to_string(), "0".to_string());

    let result = steps::dispatch(
        "a Rust file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<left_file>\" containing a function with structure \"<structure>\" and identifiers \"<left_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "a Rust file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [a Rust file \"<right_file>\" containing a function with structure \"<structure>\" and identifiers \"<right_ids>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("no duplicate pair is reported", &mut world, &example);
    assert!(
        result.success,
        "step failed [no duplicate pair is reported]: {}",
        result.message
    );
}

#[test]
fn unreadable_or_unparsable_input_is_an_error_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("condition".to_string(), "path does not exist".to_string());
    example.insert("args".to_string(), "./does-not-exist".to_string());
    example.insert("exit_code".to_string(), "2".to_string());

    let result = steps::dispatch("the input condition \"<condition>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the input condition \"<condition>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stderr is not empty", &mut world, &example);
    assert!(
        result.success,
        "step failed [stderr is not empty]: {}",
        result.message
    );
}

#[test]
fn unreadable_or_unparsable_input_is_an_error_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("condition".to_string(), "source fails to parse".to_string());
    example.insert("args".to_string(), "./src".to_string());
    example.insert("exit_code".to_string(), "2".to_string());

    let result = steps::dispatch("the input condition \"<condition>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the input condition \"<condition>\"]: {}",
        result.message
    );
    let result = steps::dispatch(
        "I run drywall with the arguments \"<args>\"",
        &mut world,
        &example,
    );
    assert!(
        result.success,
        "step failed [I run drywall with the arguments \"<args>\"]: {}",
        result.message
    );
    let result = steps::dispatch("the exit code is \"<exit_code>\"", &mut world, &example);
    assert!(
        result.success,
        "step failed [the exit code is \"<exit_code>\"]: {}",
        result.message
    );
    let result = steps::dispatch("stderr is not empty", &mut world, &example);
    assert!(
        result.success,
        "step failed [stderr is not empty]: {}",
        result.message
    );
}
