// GENERATED by acceptance-entrypoint-generator — DO NOT EDIT

mod runtime {
    include!("../acceptance/runtime/mod.rs");
}
mod steps {
    include!("../acceptance/steps/scaffold_cli_steps.rs");
}

use runtime::World;
use std::collections::HashMap;

#[test]
fn binary_accepts_path_arguments_and_exits_cleanly_example_1() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("args".to_string(), "./src".to_string());

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"<args>\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"<args>\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
}

#[test]
fn binary_accepts_path_arguments_and_exits_cleanly_example_2() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("args".to_string(), "./src ./features".to_string());

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"<args>\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"<args>\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
}

#[test]
fn binary_accepts_path_arguments_and_exits_cleanly_example_3() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("args".to_string(), "".to_string());

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"<args>\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"<args>\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
}

#[test]
fn binary_accepts_path_arguments_and_exits_cleanly_example_4() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();
    example.insert("args".to_string(), "./does-not-exist".to_string());

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"<args>\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"<args>\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
}
