// GENERATED by acceptance-entrypoint-generator — DO NOT EDIT

mod runtime {
    include!("../acceptance/runtime/mod.rs");
}
mod steps {
    include!("../acceptance/steps/scaffold_cli_steps.rs");
}

use runtime::World;
use std::collections::HashMap;

#[test]
fn binary_exits_cleanly_with_no_arguments() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
    let result = steps::dispatch("stderr is empty", &mut world, &example);
    assert!(result.success, "step failed [stderr is empty]: {}", result.message);
}

#[test]
fn binary_exits_cleanly_with_a_single_path_argument() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"./src\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"./src\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
    let result = steps::dispatch("stderr is empty", &mut world, &example);
    assert!(result.success, "step failed [stderr is empty]: {}", result.message);
}

#[test]
fn binary_exits_cleanly_with_multiple_path_arguments() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"./src ./features\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"./src ./features\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
    let result = steps::dispatch("stderr is empty", &mut world, &example);
    assert!(result.success, "step failed [stderr is empty]: {}", result.message);
}

#[test]
fn binary_exits_cleanly_with_a_nonexistent_path_argument() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"./does-not-exist\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"./does-not-exist\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
    let result = steps::dispatch("stderr contains no panic text", &mut world, &example);
    assert!(result.success, "step failed [stderr contains no panic text]: {}", result.message);
}

#[test]
fn minimal_rust_source_parses_without_error() {
    let mut world = World::new();
    let mut example: HashMap<String, String> = HashMap::new();

    let result = steps::dispatch("the drywall release binary is built", &mut world, &example);
    assert!(result.success, "step failed [the drywall release binary is built]: {}", result.message);
    let result = steps::dispatch("a minimal Rust source directory exists at \"./tmp/qa-minimal\"", &mut world, &example);
    assert!(result.success, "step failed [a minimal Rust source directory exists at \"./tmp/qa-minimal\"]: {}", result.message);
    let result = steps::dispatch("the binary is run with the arguments \"./tmp/qa-minimal\"", &mut world, &example);
    assert!(result.success, "step failed [the binary is run with the arguments \"./tmp/qa-minimal\"]: {}", result.message);
    let result = steps::dispatch("the exit code is 0", &mut world, &example);
    assert!(result.success, "step failed [the exit code is 0]: {}", result.message);
    let result = steps::dispatch("stdout is empty", &mut world, &example);
    assert!(result.success, "step failed [stdout is empty]: {}", result.message);
    let result = steps::dispatch("stderr is empty", &mut world, &example);
    assert!(result.success, "step failed [stderr is empty]: {}", result.message);
}
