#!/usr/bin/env python3
"""Acceptance entrypoint generator for drywall.
Reads JSON IR and generates a Rust acceptance test file.
Usage: generate_entrypoint.py <json-ir> <generated-test-output-dir>

Output files are placed in <generated-test-output-dir>/ and use
include!() paths relative to their final location.
"""

import json
import os
import re
import subprocess
import sys


def slug(name):
    s = name.lower()
    s = re.sub(r'[^a-z0-9]+', '_', s)
    s = s.strip('_')
    s = re.sub(r'_+', '_', s)
    return s


def rust_fn_name(name):
    return slug(name)


def escape_rust_str(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def relative_path_from(from_file, to_path):
    """Compute a relative path from the directory of from_file to to_path."""
    from_dir = os.path.dirname(os.path.abspath(from_file))
    return os.path.relpath(os.path.abspath(to_path), from_dir)


def generate_test_file(ir, output_file, runtime_path, steps_path):
    scenarios = ir.get('scenarios', [])
    lines = [
        '// GENERATED by acceptance-entrypoint-generator — DO NOT EDIT',
        '',
        'mod runtime {',
        f'    include!("{runtime_path}");',
        '}',
        'mod steps {',
        f'    include!("{steps_path}");',
        '}',
        '',
        'use runtime::World;',
        'use std::collections::HashMap;',
        '',
    ]

    for scenario in scenarios:
        sname = scenario['name']
        steps = scenario['steps']
        raw_examples = scenario.get('examples', [])
        examples = raw_examples if raw_examples else [{}]
        for idx, example in enumerate(examples, 1):
            fn_name = f'{rust_fn_name(sname)}_example_{idx}' if raw_examples else rust_fn_name(sname)
            lines.append('#[test]')
            lines.append(f'fn {fn_name}() {{')
            lines.append('    let mut world = World::new();')
            lines.append('    let mut example: HashMap<String, String> = HashMap::new();')
            for k, v in example.items():
                ek = escape_rust_str(k)
                ev = escape_rust_str(v)
                lines.append(f'    example.insert("{ek}".to_string(), "{ev}".to_string());')
            lines.append('')
            for step in steps:
                text = step['text']
                et = escape_rust_str(text)
                lines.append(f'    let result = steps::dispatch("{et}", &mut world, &example);')
                lines.append(
                    f'    assert!(result.success, "step failed [{et}]: {{}}", result.message);'
                )
            lines.append('}')
            lines.append('')

    with open(output_file, 'w') as f:
        f.write('\n'.join(lines))


def metadata_filename(feature_path):
    s = feature_path.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    s = s.strip('-')
    return s + '.json'


def sha256_file(path):
    result = subprocess.run(
        ['shasum', '-a', '256', path], capture_output=True, text=True
    )
    return result.stdout.split()[0]


def main():
    if len(sys.argv) != 3:
        print('usage: acceptance-entrypoint-generator <json-ir> <generated-test-output-dir>', file=sys.stderr)
        sys.exit(2)

    ir_file = sys.argv[1]
    output_dir = sys.argv[2]

    if not os.path.isfile(ir_file):
        print(f'error: IR file not found: {ir_file}', file=sys.stderr)
        sys.exit(1)

    try:
        with open(ir_file) as f:
            ir = json.load(f)
    except Exception as e:
        print(f'error: failed to parse IR file: {e}', file=sys.stderr)
        sys.exit(1)

    os.makedirs(os.path.join(output_dir, 'metadata'), exist_ok=True)

    feature_name = ir.get('name', 'unknown')
    output_file = os.path.join(output_dir, f'{slug(feature_name)}_acceptance_test.rs')

    # Derive paths from script location: scripts/ is in acceptance/scripts/
    script_dir = os.path.dirname(os.path.abspath(__file__))
    acceptance_dir = os.path.dirname(script_dir)  # acceptance/

    runtime_abs = os.path.join(acceptance_dir, 'runtime', 'mod.rs')
    steps_abs = os.path.join(acceptance_dir, 'steps', 'scaffold_cli_steps.rs')

    output_file_abs = os.path.abspath(output_file)
    runtime_rel = os.path.relpath(runtime_abs, os.path.dirname(output_file_abs))
    steps_rel = os.path.relpath(steps_abs, os.path.dirname(output_file_abs))

    try:
        generate_test_file(ir, output_file, runtime_rel, steps_rel)
    except Exception as e:
        print(f'error: failed to generate test file: {e}', file=sys.stderr)
        sys.exit(1)

    print(f'Generated: {output_file}')

    # Write metadata
    feature_path = 'features/scaffold_cli.feature'
    meta_filename = metadata_filename(feature_path)
    metadata_file = os.path.join(output_dir, 'metadata', meta_filename)
    impl_hash = sha256_file(output_file)

    metadata = {
        'schema_version': 1,
        'feature_path': feature_path,
        'ir_path': ir_file,
        'implementation_hash': f'sha256:{impl_hash}',
        'hash_scope': 'generated_files',
        'generated_files': [output_file],
    }
    with open(metadata_file, 'w') as f:
        json.dump(metadata, f, indent=2)
    print(f'Metadata: {metadata_file}')


if __name__ == '__main__':
    main()
